name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray
  - pip
  - s3fs
  - geoviews
  - hvplot
  - cartopy
  - holoviews
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - h5netcdf
  - pip:
    - kubernetes
    - intake-xarray
    - graphviz
